<!doctype html>
<html>
<head>
<title>2018-3-20-23-0-22.html</title>
<link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,500,700" rel="stylesheet">
<style>
.thumbnail { max-width: 320px; max-height: 200px; }
h4 { font-weight: normal; font-family: 'Roboto Mono', monospace; font-size: 11px; }
h4.log-info { color: #333333; }
h4.log-error { color: #EA4335; }
</style>
</head>
<body>
<h4 class="log-info">[info] Playing test case Search Test Suite / Search</h4><h4 class="log-info">[info] Time: Tue Mar 20 2018 22:59:14 GMT-0400 (Eastern Daylight Time) Timestamp: 1521601154590</h4><h4 class="log-info">[info] OS: Windows Version: 10</h4><h4 class="log-info">[info] Browser: Chrome Version: 65.0</h4><h4 class="log-info">[info] Executing: | open | http://127.0.0.1/ |  |</h4><h4 class="log-info">[info] Executing: | click | id=loginButton |  |</h4><h4 class="log-info">[info] Executing: | click | name=username |  |</h4><h4 class="log-info">[info] Executing: | type | name=username | MyName |</h4><h4 class="log-info">[info] Executing: | type | name=password | test123 |</h4><h4 class="log-info">[info] Executing: | click | //form[@id='loginForm']/div/div/section/div/div/div/center |  |</h4><h4 class="log-info">[info] Executing: | click | //input[@id='loginButton'] |  |</h4><h4 class="log-info">[info] Executing: | click | id=global-search-01 |  |</h4><h4 class="log-info">[info] Executing: | type | id=global-search-01 | Java |</h4><h4 class="log-info">[info] Executing: | click | //header/div |  |</h4><h4 class="log-info">[info] Executing: | click | id=global-search-01 |  |</h4><h4 class="log-info">[info] Executing: | sendKeys | id=global-search-01 | ${KEY_ENTER} |</h4><h4 class="log-info">[info] Executing: | type | id=global-search-01 | Java |</h4><h4 class="log-info">[info] Executing: | click | //div[@id='post']/div[2] |  |</h4><h4 class="log-info">[info] Wait until the element is found</h4><h4 class="log-info">[info] Executing: | click | //div[@id='post']/div[2] |  |</h4><h4 class="log-info">[info] Wait until the element is found</h4><h4 class="log-info">[info] Executing: | click | //div[@id='post']/div[2] |  |</h4><h4 class="log-info">[info] Executing: | click | link=Java Test 1 |  |</h4><h4 class="log-info">[info] Wait for the new page to be fully loaded</h4><h4 class="log-info">[info] Executing: | click | id=content |  |</h4><h4 class="log-info">[info] Executing: | click | //button[@onclick="location.href='..'"] |  |</h4><h4 class="log-info">[info] Executing: | click | xpath=(//img[@alt='Smiley face'])[2] |  |</h4><h4 class="log-info">[info] Time: Tue Mar 20 2018 23:00:20 GMT-0400 (Eastern Daylight Time) Timestamp: 1521601220017</h4><h4 class="log-info">[info] Test case passed</h4>